import type { NextPage } from "next";
import Head from "next/head";
import MintCardContent from "components/MintCardContent";
import OwnedNFTsComponent from "components/OwnedNFTsComponent";
import classNames from "classnames";
import Title from "components/Title";
import polygonIcon from "cryptocurrency-icons/svg/icon/matic.svg";
import ethereumIcon from "cryptocurrency-icons/svg/icon/eth.svg";

const squareSrc = "https://placehold.co/400x400";

const Home: NextPage = () => {
  return (
    <div className="h-full flex border flex-col justify-center items-center">
      <Head>
        <title>Typescript Eth Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full p-2">
        <div className="h-full flex flex-col lg:flex-row gap-4">
          <div className="w-full lg:w-2/3 flex flex-col">
            {/* Metadata Display */}
            <div className="border border-black flex flex-col md:flex-row items-center md:items-start">
              <div className="w-[300px] h-[300px] xl:w-[400px] xl:h-[400px] aspect-square p-4">
                <img
                  src={squareSrc}
                  className="w-full h-full  border border-black"
                />
              </div>
              <div className="p-4">
                <div className="border-b-2 pb-2 mb-4 flex flex-row justify-between">
                  <Title text="Interoperable Wearable Account" />
                  <div className="flex flex-row gap-1">
                    <img {...polygonIcon} />
                    <img {...ethereumIcon} />
                  </div>
                </div>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                  {Array.from({ length: 3 }).map((_, i) => {
                    return (
                      <div key={i}>
                        <img
                          src={squareSrc}
                          className={classNames("h-auto max-w-full")}
                        />
                      </div>
                    );
                  })}
                </div>
                <div className="pt-4">
                  <p className="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Viverra nibh cras pulvinar mattis nunc sed. Orci
                    sagittis eu volutpat odio facilisis. Nisl tincidunt eget
                    nullam non nisi. Augue neque gravida in fermentum. Sagittis
                    eu volutpat odio facilisis mauris. Aenean et tortor at
                    risus. Nunc eget lorem dolor sed. Aliquam malesuada bibendum
                    arcu vitae elementum curabitur vitae. Aliquet porttitor
                    lacus luctus accumsan tortor posuere ac. A diam maecenas sed
                    enim ut sem viverra.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full lg:w-1/3 flex flex-col gap-4">
            <MintCardContent />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
