import type { NextPage } from "next";
import Head from "next/head";
import MintCardContent from "components/MintCardContent";
import Title from "components/Title";
import useAccountItems from "hooks/useAccountItems";
import useAccountNft from "hooks/useAccountNft";
import AccountItem from "components/AccountItem";
import Card from "components/Card";
import { icons } from "shared-config";

const Home: NextPage = () => {
  const { itemsMetadata } = useAccountItems();
  const { metadata } = useAccountNft();

  return (
    <div className="h-full flex flex-col justify-center items-center">
      <Head>
        <title>Gaian Wearable</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-full h-full">
        <div className="h-full flex flex-col lg:flex-row gap-4">
          <div className="w-full h-full lg:w-2/3 flex flex-col flex-grow">
            {/* Metadata Display */}
            <Card className="h-full">
              <div className="flex flex-col md:flex-row items-center md:items-start">
                <div className="w-[300px] h-[300px] xl:w-[400px] xl:h-[400px] aspect-square p-4">
                  {metadata && (
                    <img
                      src={metadata.image}
                      className="w-full h-full border"
                    />
                  )}
                </div>
                <div className="p-4">
                  <div className="border-b-2 pb-2 mb-4 flex flex-row justify-between">
                    <Title text={metadata?.name ?? ""} />
                    <div className="flex flex-row gap-1">
                      <img {...icons.ethereum} className="h-6 w-6" />
                      <img {...icons.polygon} className="h-6 w-6" />
                    </div>
                  </div>
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                    {itemsMetadata.map((itemMetadata, i) => {
                      return <AccountItem key={i} {...itemMetadata} />;
                    })}
                  </div>
                  <div className="pt-4">
                    <p className="text-justify font-main">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Viverra nibh cras pulvinar mattis nunc sed. Orci
                      sagittis eu volutpat odio facilisis. Nisl tincidunt eget
                      nullam non nisi. Augue neque gravida in fermentum.
                      Sagittis eu volutpat odio facilisis mauris. Aenean et
                      tortor at risus. Nunc eget lorem dolor sed. Aliquam
                      malesuada bibendum arcu vitae elementum curabitur vitae.
                      Aliquet porttitor lacus luctus accumsan tortor posuere ac.
                      A diam maecenas sed enim ut sem viverra.
                    </p>
                  </div>
                </div>
              </div>
            </Card>
          </div>
          <div className="w-full lg:w-1/3">
            <MintCardContent />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
